os: Windows Server 2012
version: '{build}'
skip_tags: true
clone_depth: 10
branches:
  only:
    - master
  except:
    - gh-pages
init:
  - git config --global core.autocrlf true
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://downloads.apache.org/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET M2_HOME=C:\maven\apache-maven-3.2.5
  - cmd: SET PATH=%M2_HOME%\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: git config --global core.autocrlf
  - cmd: mvn --version
  - cmd: java -version
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
build_script:
  - mvn clean install
  - ps: echo "Size of caches (bytes):"
  - ps: Get-ChildItem -Recurse 'C:\maven' | Measure-Object -Property Length -Sum
  - ps: Get-ChildItem -Recurse 'C:\Users\appveyor\.m2' | Measure-Object -Property Length -Sum
