version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0

workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          filters:
            branches:
              only: master
          app-name: methods-distance
          context: heroku-context
