package com.github.sevntu.checkstyle;

import com.github.sevntu.checkstyle.domain.Dependencies;
import com.github.sevntu.checkstyle.module.DependencyInformationConsumer;
import com.github.sevntu.checkstyle.common.MethodCallDependencyCheckInvoker;
import com.github.sevntu.checkstyle.ordering.Ordering;
import com.github.sevntu.checkstyle.reordering.TopologicalMethodReorderer;
import com.github.sevntu.checkstyle.utils.FileUtils;
import com.github.sevntu.checkstyle.dsm.DependencyInfoMatrixSerializer;
import com.puppycrawl.tools.checkstyle.api.CheckstyleException;
import com.puppycrawl.tools.checkstyle.api.Configuration;

import java.io.File;
import java.util.Collections;
import java.util.List;
import java.util.Map;

/**
 * Application entry point that accepts file path and generates
 * DSM for initial methods ordering of class and DSM for method
 * ordering generated by topological sorting algorithm.
 */
public final class ReorderingCli {

    private ReorderingCli() { }

    public static void main(String... args) throws CheckstyleException {

        final Map<String, String> attributes = Collections.singletonMap("screenLinesCount", "50");

        final DependencyInformationSerializer consumer = new DependencyInformationSerializer();

        final MethodCallDependencyCheckInvoker runner =
            new MethodCallDependencyCheckInvoker(attributes, consumer);

        final List<File> files = Collections.singletonList(new File(args[0]));
        runner.invoke(files);
    }

    private static final class DependencyInformationSerializer implements
        DependencyInformationConsumer {

        private Configuration configuration;

        private DependencyInformationSerializer() { }

        @Override
        public void setConfiguration(Configuration config) {
            this.configuration = config;
        }

        @Override
        public void accept(String filePath, Dependencies dependencies) {
            final String baseName = new File(filePath).getName();
            final String source = FileUtils.getFileContents(filePath);
            final Ordering initialOrdering = new Ordering(dependencies);
            final Ordering topologicalOrdering = new TopologicalMethodReorderer()
                .reorder(initialOrdering);
            DependencyInfoMatrixSerializer.writeToFile(
                source, initialOrdering, configuration, baseName + ".initial.html");
            DependencyInfoMatrixSerializer.writeToFile(
                source, topologicalOrdering, configuration, baseName + ".topological.html");
        }
    }
}
